[github_hosted]
readme_listings = [
    "https://github.com/APA-Technology-Division/urban-and-regional-planning-resources",
    "https://github.com/Agri-Hub/Callisto-Dataset-Collection",
    "https://github.com/CUTR-at-USF/awesome-transit",
    "https://github.com/ESIPFed/Awesome-Earth-Artificial-Intelligence",
    "https://github.com/Green-Software-Foundation/awesome-green-software",
    "https://github.com/IndEcol/Dashboard",
    "https://github.com/IrishMarineInstitute/awesome-erddap",
    "https://github.com/KKulma/climate-change-data",
    "https://github.com/arctic-risk/awesome-arctic-data",
    "https://github.com/awesome-cryosphere/cryosphere-links",
    "https://github.com/awesome-spectral-indices/awesome-spectral-indices",
    "https://github.com/blutjens/awesome-forests/",
    "https://github.com/brycejohnston/awesome-agriculture",
    "https://github.com/chrisleaman/awesome-coastal",
    "https://github.com/daviddao/code-against-climate-change",
    "https://github.com/geco-bern/ingestr/",
    "https://github.com/github/GreenSoftwareDirectory",
    "https://github.com/jaychempan/Awesome-LWMs",
    "https://github.com/kr-stn/awesome-sentinel",
    "https://github.com/lf-energy/lfenergy-landscape",
    "https://github.com/nglgzz/awesome-clean-tech",
    "https://github.com/opengeos/geospatial-data-catalogs",
    "https://github.com/pangeo-data/awesome-open-climate-science",
    "https://github.com/philippgaertner/awesome-earth-engine-apps",
    "https://github.com/philsturgeon/awesome-earth",
    "https://github.com/pogopaule/awesome-sustainability-jobs",
    "https://github.com/px39n/Awesome-Vegetation-Index",
    "https://github.com/raoulcollenteur/Python-Hydrology-Tools",
    "https://github.com/samapriya/awesome-gee-community-datasets/",
    "https://github.com/softwareunderground/awesome-open-geoscience",
    "https://github.com/wenhwu/awesome-remote-sensing-change-detection",
]

[webpages]
html = []

[faults]
urls = []
invalid_urls = []
