[github_hosted]
readme_listings = [
    "https://github.com/Agri-Hub/Callisto-Dataset-Collection",
    "https://github.com/ESIPFed/Awesome-Earth-Artificial-Intelligence",
    "https://github.com/Green-Software-Foundation/awesome-green-software",
    "https://github.com/IrishMarineInstitute/awesome-erddap",
    "https://github.com/awesome-cryosphere/cryosphere-links",
    "https://github.com/brycejohnston/awesome-agriculture",
    "https://github.com/chrisleaman/awesome-coastal",
    "https://github.com/github/GreenSoftwareDirectory",
    "https://github.com/jaychempan/Awesome-LWMs",
    "https://github.com/kr-stn/awesome-sentinel",
    "https://github.com/pangeo-data/awesome-open-climate-science",
]

[webpages]
html = []

[faults]
urls = []
invalid_urls = []
