[[github_hosted.readme_listings]]
url = "https://github.com/16EAGLE/getSpatialData"
license = "GNU General Public License v3.0"

[[github_hosted.readme_listings]]
url = "https://github.com/APA-Technology-Division/urban-and-regional-planning-resources"
license = "Creative Commons Zero v1.0 Universal"

[[github_hosted.readme_listings]]
url = "https://github.com/Agri-Hub/Callisto-Dataset-Collection"
license = "Apache License 2.0"

[[github_hosted.readme_listings]]
url = "https://github.com/CS-SI/eodag"
license = "Apache License 2.0"

[[github_hosted.readme_listings]]
url = "https://github.com/CUTR-at-USF/awesome-transit"
license = "Creative Commons Zero v1.0 Universal"

[[github_hosted.readme_listings]]
url = "https://github.com/Clay-foundation/model"
license = "Apache License 2.0"

[[github_hosted.readme_listings]]
url = "https://github.com/DataONEorg/d1_python"
license = "Apache License 2.0"

[[github_hosted.readme_listings]]
url = "https://github.com/DataONEorg/rdataone"
license = "?"

[[github_hosted.readme_listings]]
url = "https://github.com/ECCC-MSC/msc-pygeoapi"
license = "MIT License"

[[github_hosted.readme_listings]]
url = "https://github.com/EDIorg/ecocomDP"
license = "Other"

[[github_hosted.readme_listings]]
url = "https://github.com/ESIPFed/Awesome-Earth-Artificial-Intelligence"
license = "Creative Commons Zero v1.0 Universal"

[[github_hosted.readme_listings]]
url = "https://github.com/Greater-Wellington-Regional-Council/Environmental-Outcomes-Platform"
license = "MIT License"

[[github_hosted.readme_listings]]
url = "https://github.com/Green-Software-Foundation/awesome-green-software"
license = "Other"

[[github_hosted.readme_listings]]
url = "https://github.com/IndEcol/Dashboard"
license = "?"

[[github_hosted.readme_listings]]
url = "https://github.com/IrishMarineInstitute/awesome-erddap"
license = "Creative Commons Zero v1.0 Universal"

[[github_hosted.readme_listings]]
url = "https://github.com/JuliaDataCubes/EarthDataLab.jl"
license = "Other"

[[github_hosted.readme_listings]]
url = "https://github.com/KKulma/climate-change-data"
license = "?"

[[github_hosted.readme_listings]]
url = "https://github.com/NASA-IMPACT/veda-ui"
license = "Other"

[[github_hosted.readme_listings]]
url = "https://github.com/NEONScience/NEON-utilities"
license = "GNU Affero General Public License v3.0"

[[github_hosted.readme_listings]]
url = "https://github.com/Pierre-VF/OpenClimateResources"
license = "MIT License"

[[github_hosted.readme_listings]]
url = "https://github.com/RolnickLab/OpenForest"
license = "Apache License 2.0"

[[github_hosted.readme_listings]]
url = "https://github.com/USGCRP/gcis"
license = "Other"

[[github_hosted.readme_listings]]
url = "https://github.com/Unidata/siphon"
license = 'BSD 3-Clause "New" or "Revised" License'

[[github_hosted.readme_listings]]
url = "https://github.com/adarsh-singh01/PrithWe"
license = "Other"

[[github_hosted.readme_listings]]
url = "https://github.com/alan-turing-institute/environmental-ds-book"
license = "Creative Commons Attribution 4.0 International"

[[github_hosted.readme_listings]]
url = "https://github.com/allenai/satlas"
license = "Apache License 2.0"

[[github_hosted.readme_listings]]
url = "https://github.com/arctic-risk/awesome-arctic-data"
license = "Creative Commons Zero v1.0 Universal"

[[github_hosted.readme_listings]]
url = "https://github.com/awesome-cryosphere/cryosphere-links"
license = "?"

[[github_hosted.readme_listings]]
url = "https://github.com/awesome-spectral-indices/awesome-spectral-indices"
license = "MIT License"

[[github_hosted.readme_listings]]
url = "https://github.com/blaylockbk/SynopticPy"
license = "MIT License"

[[github_hosted.readme_listings]]
url = "https://github.com/blutjens/awesome-forests/"
license = "Creative Commons Zero v1.0 Universal"

[[github_hosted.readme_listings]]
url = "https://github.com/brycejohnston/awesome-agriculture"
license = "Other"

[[github_hosted.readme_listings]]
url = "https://github.com/chrisleaman/awesome-coastal"
license = "Creative Commons Zero v1.0 Universal"

[[github_hosted.readme_listings]]
url = "https://github.com/daviddao/code-against-climate-change"
license = "?"

[[github_hosted.readme_listings]]
url = "https://github.com/digitalearthafrica/deafrica-sandbox-notebooks"
license = "Apache License 2.0"

[[github_hosted.readme_listings]]
url = "https://github.com/edgi-govdata-archiving/ECHO-Cross-Program"
license = "GNU General Public License v3.0"

[[github_hosted.readme_listings]]
url = "https://github.com/eea/geonetwork-eea"
license = "GNU General Public License v2.0"

[[github_hosted.readme_listings]]
url = "https://github.com/geco-bern/ingestr/"
license = "?"

[[github_hosted.readme_listings]]
url = "https://github.com/github/GreenSoftwareDirectory"
license = "MIT License"

[[github_hosted.readme_listings]]
url = "https://github.com/jaychempan/Awesome-LWMs"
license = "MIT License"

[[github_hosted.readme_listings]]
url = "https://github.com/kapadia/usgs"
license = "ISC License"

[[github_hosted.readme_listings]]
url = "https://github.com/kr-stn/awesome-sentinel"
license = "Creative Commons Attribution 4.0 International"

[[github_hosted.readme_listings]]
url = "https://github.com/lf-energy/lfenergy-landscape"
license = "Apache License 2.0"

[[github_hosted.readme_listings]]
url = "https://github.com/michaeldavie/env_canada"
license = "MIT License"

[[github_hosted.readme_listings]]
url = "https://github.com/microsoft/AIforEarthDataSets"
license = "MIT License"

[[github_hosted.readme_listings]]
url = "https://github.com/microsoft/PlanetaryComputerDataCatalog"
license = "MIT License"

[[github_hosted.readme_listings]]
url = "https://github.com/mysociety/caps"
license = "Other"

[[github_hosted.readme_listings]]
url = "https://github.com/nasa/cmr-stac"
license = "Other"

[[github_hosted.readme_listings]]
url = "https://github.com/nasa/earthdata-search"
license = "Other"

[[github_hosted.readme_listings]]
url = "https://github.com/nglgzz/awesome-clean-tech"
license = "Creative Commons Zero v1.0 Universal"

[[github_hosted.readme_listings]]
url = "https://github.com/nsidc/earthaccess"
license = "MIT License"

[[github_hosted.readme_listings]]
url = "https://github.com/nychealth/EH-dataportal"
license = "?"

[[github_hosted.readme_listings]]
url = "https://github.com/opengeos/geospatial-data-catalogs"
license = "MIT License"

[[github_hosted.readme_listings]]
url = "https://github.com/opengeos/leafmap"
license = "MIT License"

[[github_hosted.readme_listings]]
url = "https://github.com/pangeo-data/awesome-open-climate-science"
license = "Creative Commons Zero v1.0 Universal"

[[github_hosted.readme_listings]]
url = "https://github.com/philippgaertner/awesome-earth-engine-apps"
license = "MIT License"

[[github_hosted.readme_listings]]
url = "https://github.com/philsturgeon/awesome-earth"
license = "?"

[[github_hosted.readme_listings]]
url = "https://github.com/piersyork/owidR"
license = "Other"

[[github_hosted.readme_listings]]
url = "https://github.com/pogopaule/awesome-sustainability-jobs"
license = "Other"

[[github_hosted.readme_listings]]
url = "https://github.com/px39n/Awesome-Vegetation-Index"
license = "?"

[[github_hosted.readme_listings]]
url = "https://github.com/pydap/pydap"
license = "MIT License"

[[github_hosted.readme_listings]]
url = "https://github.com/r-earthengine/ee_extra"
license = "Other"

[[github_hosted.readme_listings]]
url = "https://github.com/r-spatial/rgee"
license = "Other"

[[github_hosted.readme_listings]]
url = "https://github.com/rOpenGov/eurostat"
license = "Other"

[[github_hosted.readme_listings]]
url = "https://github.com/rOpenGov/giscoR"
license = "GNU General Public License v3.0"

[[github_hosted.readme_listings]]
url = "https://github.com/radiantearth/radiant-mlhub"
license = "?"

[[github_hosted.readme_listings]]
url = "https://github.com/raoulcollenteur/Python-Hydrology-Tools"
license = "?"

[[github_hosted.readme_listings]]
url = "https://github.com/resource-watch/resource-watch"
license = "MIT License"

[[github_hosted.readme_listings]]
url = "https://github.com/ropensci/FedData"
license = "Other"

[[github_hosted.readme_listings]]
url = "https://github.com/ropensci/epair"
license = "GNU General Public License v3.0"

[[github_hosted.readme_listings]]
url = "https://github.com/samapriya/awesome-gee-community-datasets/"
license = "Creative Commons Attribution 4.0 International"

[[github_hosted.readme_listings]]
url = "https://github.com/samuelrince/awesome-green-ai"
license = "Creative Commons Zero v1.0 Universal"

[[github_hosted.readme_listings]]
url = "https://github.com/sentinel-hub/custom-scripts"
license = "Creative Commons Attribution Share Alike 4.0 International"

[[github_hosted.readme_listings]]
url = "https://github.com/smart-data-models/dataModel.Environment"
license = "Other"

[[github_hosted.readme_listings]]
url = "https://github.com/softwareunderground/awesome-open-geoscience"
license = "Creative Commons Zero v1.0 Universal"

[[github_hosted.readme_listings]]
url = "https://github.com/stac-utils/stac-index"
license = "Apache License 2.0"

[[github_hosted.readme_listings]]
url = "https://github.com/wenhwu/awesome-remote-sensing-change-detection"
license = "?"

[[gitlab_hosted.readme_listings]]
url = "https://gitlab.com/geoharmonizer_inea/eumap"
license = "?"

[[webpages.html]]
url = "https://energy.acm.org/resources/"
license = "?"

[[webpages.html]]
url = "https://opensustain.tech/"
license = "Creative Commons Attribution 4.0 International"

[faults]
invalid_urls = []
[[faults.urls]]
url = "http://sciencepolicy.colorado.edu/icecaps/research/media_coverage/"
license = "?"

[[faults.urls]]
url = "https://archive.ceda.ac.uk/"
license = "?"

[[faults.urls]]
url = "https://cds.climate.copernicus.eu/"
license = "?"

[[faults.urls]]
url = "https://climate.esa.int/en/odp/"
license = "?"

[[faults.urls]]
url = "https://data.apps.fao.org/"
license = "?"

[[faults.urls]]
url = "https://data.subak.org/"
license = "?"

[[faults.urls]]
url = "https://db.cger.nies.go.jp/portal/geds/index"
license = "?"

[[faults.urls]]
url = "https://energy.acm.org/resources/"
license = "?"

[[faults.urls]]
url = "https://globalenergymonitor.org/"
license = "?"

[[faults.urls]]
url = "https://globalfishingwatch.org/"
license = "?"

[[faults.urls]]
url = "https://globalsolaratlas.info/"
license = "?"

[[faults.urls]]
url = "https://globalwindatlas.info/"
license = "?"

[[faults.urls]]
url = "https://maps.opendatascience.eu/"
license = "?"

[[faults.urls]]
url = "https://podaac.jpl.nasa.gov/cloud-datasets"
license = "?"

[[faults.urls]]
url = "https://power.larc.nasa.gov/"
license = "?"

[[faults.urls]]
url = "https://wiki.openmod-initiative.org/wiki/Open_Models"
license = "?"

[[faults.urls]]
url = "https://www.earthdata.nasa.gov/"
license = "?"
