#
# YAML file configuring the actions to take when releasing to production
#
# > Syntax tips here: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
#
name: Updating the data

on: 
  workflow_dispatch:      
    logLevel:
      description: 'Log level'
      required: true
      default: 'warning'
      type: choice
      options:
        - info
        - warning
        - debug
  schedule:
    - cron: '25 5 * * TUE'

jobs:
  build-and-run-discovery:
    name: Discover new sources

    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write

    concurrency:
      group: ${{ github.workflow }}-discovery
      cancel-in-progress: true   

    steps:
      - name: "Create UV installation"
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.5.16"

      - name: "Checkout code"
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Installing packages 
        run: make install
        
      - name: Running discovery
        run: make discover
        
      - name: Defining Git identity 
        run: | 
          git config user.name github_actions
          git config user.email github_actions@pierrevf.consulting
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: "index-update/${{ github.run_id }}"
          base: "main"
          title: "Updating index"