#
# YAML file configuring the actions to take when releasing to production
#
# > Syntax tips here: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
#
name: Updating the data

on:
  workflow_dispatch:
    logLevel:
      description: 'Log level'
      required: true
      default: 'warning'
      type: choice
      options:
        - info
        - warning
        - debug
  schedule:
    - cron: '25 5 * * TUE'

jobs:
  build-and-run-discovery:
    name: Discover new sources

    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write

    concurrency:
      group: ${{ github.workflow }}-discovery
      cancel-in-progress: true

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: "Create UV installation"
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.8.0"

      - name: Installing packages
        run: uv sync --group=scripts

      - name: Running discovery
        run: make discover
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLAB_ACCESS_TOKEN: ${{ secrets.GITLAB_ACCESS_TOKEN }}

      - name: Cleaning up the code
        run: |
          make check_code || echo "Precommits modified the files"

      - name: Defining Git identity
        run: |
          git config user.name github_actions
          git config user.email github_actions@pierrevf.consulting

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: "index-update/${{ github.run_id }}"
          base: "main"
          title: "Updating index"
